import { StyleSheet, Dimensions } from "react-native";

const styles = StyleSheet.create({
    discountItem: {
        fontSize: 15,
        color: 'red',
        fontFamily: 'Rockwell',
        fontWeight: '900',
        textAlign: 'left',
    },
    containerItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        backgroundColor: 'white',
        borderRadius: 10,
        marginHorizontal: 15,
        marginVertical: 6,
        elevation: 10,
        shadowColor: '#000000',
        shadowOffset: { width: 10, height: 10 },
        shadowOpacity: 1,
    },
    containerButton: {
        flex: 0.7,
        padding: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    button: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 5,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
    },
    buttonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    containerText: {
        flex: 1,
    },
    image: {
        width: 100,
        height: 100,
        marginRight: 10,
        alignSelf: 'center',
    },
    nameItem: {
        fontSize: 18,
        color: 'black',
        fontFamily: 'Rockwell',
        fontWeight: '900',
        textAlign: 'left',
    },
    descriptionItem: {
        fontSize: 15,
        color: 'black',
        fontFamily: 'Rockwell',
        fontWeight: '100',
        textAlign: 'left',
    },
    priceItem: {
        fontSize: 15,
        color: 'black',
        fontFamily: 'Rockwell',
        fontWeight: '900',
        textAlign: 'left',
    },
    containerP: {
        flex: 1,
        backgroundColor: '#eeeeee',
        position: 'relative',
    },
    halfBackgroundLeft: {
        backgroundColor: '#4cad42',
        position: 'absolute',
        left: 0,
        width: '50%',
        height: '100%',
        zIndex: -1,
    },
    halfBackgroundRight: {
        backgroundColor: '#0c9942',
        position: 'absolute',
        right: 0,
        width: '50%',
        height: '100%',
        zIndex: -1,
    },
    searchBar: {
        height: 40,
        borderColor: '#ccc',
        borderWidth: 2,
        borderRadius: 4,
        paddingHorizontal: 10,
        margin: 10,
        backgroundColor: '#fff',
    },
    overlay: {
        backgroundColor: '#ffffff',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        zIndex: 1,

    },
    containerBarra: {
        backgroundColor: 'white',
    },
});

export default styles;
